# Generated by Django 5.1.4 on 2025-10-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guerrillaltd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='resources/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='resources/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='advisor',
            name='bio',
            field=models.TextField(verbose_name=200),
        ),
    ]
