# Generated by Django 5.1.4 on 2025-10-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guerrillaltd', '0002_resource_alter_advisor_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('category', models.CharField(default='General', max_length=100)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
